env:
  browser: true
  commonjs: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
rules: 
  import/extensions: 0
  consistent-return: 0
  no-param-reassign: 0
  global-require: 0
  import/no-dynamic-require: 0
  max-len: 0
  eqeqeq: 0
  no-console: 0
  no-unsafe-optional-chaining: 0
